@isTest
public class SalesControllerTest {
    public static testMethod void TestSalesController(){
        /*PageReference pageRef = Page.success;
        Test.setCurrentPage(pageRef);
        SalesController controller = new SalesController();
        String nextPage = controller.save().getUrl();

        ApexPages.assertEquals('/apex/failure?error=noparam', nextPage);

        ApexPages.currentPage().getParameters().put()
        */

        // test class not complete



    }
}